IF
NOT EXISTS
CREATE TABLE films
(
    film_id      int generated by default as identity primary key,
    name         varchar(50),
    description  varchar,
    release_date date,
    duration     INTEGER,
    likes        INTEGER,
    mpa_rating   varchar(5),
    rate         INTEGER,
    CONSTRAINT chk_mpa_rating CHECK (mpa_rating = 'G' OR mpa_rating = 'PG'
        OR mpa_rating = 'PG-13' OR mpa_rating = 'R' OR mpa_rating = 'NC-17')
);

IF
NOT EXISTS
CREATE TABLE users
(
    user_id  int generated by default as identity primary key,
    email    varchar(30),
    login    varchar(30),
    name     varchar(30),
    birthday date,
    UNIQUE (email)
);

IF
NOT EXISTS
CREATE TABLE users_liked_films
(
    user_id int,
    film_id int,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    FOREIGN KEY (film_id)
        REFERENCES films (film_id)
);

IF
NOT EXISTS
CREATE TABLE friendship
(
    user_id      int,
    friend_id    int,
    is_confirmed boolean,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    FOREIGN KEY (friend_id)
        REFERENCES users (user_id)
);

IF
NOT EXISTS
CREATE TABLE genres
(
    genre_id int generated by default as identity primary key,
    name     varchar(14)
);

IF
NOT EXISTS
CREATE TABLE films_genres
(
    film_id  int,
    genre_id int,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (film_id),
    FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);